USE [master]
GO

/****** Object:  Database [AdressBook]    Script Date: 2.5.2020. 9:43:41 ******/
CREATE DATABASE [AdressBook]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AdressBook', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\AdressBook.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'AdressBook_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\AdressBook_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [AdressBook] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AdressBook].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AdressBook] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AdressBook] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AdressBook] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AdressBook] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AdressBook] SET ARITHABORT OFF 
GO

ALTER DATABASE [AdressBook] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AdressBook] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AdressBook] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AdressBook] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AdressBook] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AdressBook] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AdressBook] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AdressBook] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AdressBook] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AdressBook] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AdressBook] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AdressBook] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AdressBook] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AdressBook] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AdressBook] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AdressBook] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AdressBook] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AdressBook] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AdressBook] SET  MULTI_USER 
GO

ALTER DATABASE [AdressBook] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AdressBook] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AdressBook] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AdressBook] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [AdressBook] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AdressBook] SET  READ_WRITE 
GO


