BEGIN TRANSACTION [UserDataTable]

BEGIN TRY
	SET QUOTED_IDENTIFIER ON
	SET ARITHABORT ON
	SET NUMERIC_ROUNDABORT OFF
	SET CONCAT_NULL_YIELDS_NULL ON
	SET ANSI_NULLS ON
	SET ANSI_PADDING ON
	SET ANSI_WARNINGS ON
	
	CREATE TABLE dbo.UserData(
		Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		UserName NVARCHAR(20),
		Password NVARCHAR(20));

	COMMIT TRANSACTION [UserDataTable];
END TRY

BEGIN CATCH
	ROLLBACK TRANSACTION [UserDataTable]

	SELECT	ERROR_NUMBER() AS ErrorNumber,
			ERROR_SEVERITY() AS ErrorSeverity, 
			ERROR_STATE() AS ErrorState, 
			ERROR_PROCEDURE() AS ErrorProcedure, 
			ERROR_LINE() AS ErrorLine, 
			ERROR_MESSAGE() AS ErrorMessage;
END CATCH