BEGIN TRANSACTION [ContactGroupTable]

BEGIN TRY
	SET QUOTED_IDENTIFIER ON
	SET ARITHABORT ON
	SET NUMERIC_ROUNDABORT OFF
	SET CONCAT_NULL_YIELDS_NULL ON
	SET ANSI_NULLS ON
	SET ANSI_PADDING ON
	SET ANSI_WARNINGS ON

	CREATE TABLE dbo.ContactGroup(
		Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		Name NVARCHAR(50),
		Description NVARCHAR(255),		
		ContactId INT);
		
	ALTER TABLE dbo.ContactGroup ADD CONSTRAINT [FK_ContactGroupContactId] FOREIGN KEY(ContactId)
	REFERENCES Contact (Id)

	COMMIT TRANSACTION [ContactGroupTable];
END TRY

BEGIN CATCH
	ROLLBACK TRANSACTION [ContactGroupTable]

	SELECT	ERROR_NUMBER() AS ErrorNumber,
			ERROR_SEVERITY() AS ErrorSeverity, 
			ERROR_STATE() AS ErrorState, 
			ERROR_PROCEDURE() AS ErrorProcedure, 
			ERROR_LINE() AS ErrorLine, 
			ERROR_MESSAGE() AS ErrorMessage;
END CATCH