BEGIN TRANSACTION [ContactsTable]

BEGIN TRY
	SET QUOTED_IDENTIFIER ON
	SET ARITHABORT ON
	SET NUMERIC_ROUNDABORT OFF
	SET CONCAT_NULL_YIELDS_NULL ON
	SET ANSI_NULLS ON
	SET ANSI_PADDING ON
	SET ANSI_WARNINGS ON

	CREATE TABLE dbo.Contacts(
		Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		Title NVARCHAR(100) NOT NULL,
		Name NVARCHAR(50),
		Email NVARCHAR(50),
		UserId INT NOT NULL,
		PhoneNumberId INT NOT NULL,
		ContactGroupId INT);

	ALTER TABLE dbo.Contacts ADD CONSTRAINT [FK_UserId] FOREIGN KEY(UserId)
	REFERENCES UserData (Id)

	ALTER TABLE dbo.Contacts ADD CONSTRAINT [FK_PhoneNumberId] FOREIGN KEY(PhoneNumberId)
	REFERENCES PhoneNumber (Id)

	ALTER TABLE dbo.Contacts ADD CONSTRAINT [FK_ContactGroupId] FOREIGN KEY(ContactGroupId)
	REFERENCES ContactGroup (Id)


	COMMIT TRANSACTION [ContactsTable];
END TRY

BEGIN CATCH
	ROLLBACK TRANSACTION [ContactsTable]

	SELECT	ERROR_NUMBER() AS ErrorNumber,
			ERROR_SEVERITY() AS ErrorSeverity, 
			ERROR_STATE() AS ErrorState, 
			ERROR_PROCEDURE() AS ErrorProcedure, 
			ERROR_LINE() AS ErrorLine, 
			ERROR_MESSAGE() AS ErrorMessage;
END CATCH