BEGIN TRANSACTION [Contact_ContactGroupTable]

BEGIN TRY
	SET QUOTED_IDENTIFIER ON
	SET ARITHABORT ON
	SET NUMERIC_ROUNDABORT OFF
	SET CONCAT_NULL_YIELDS_NULL ON
	SET ANSI_NULLS ON
	SET ANSI_PADDING ON
	SET ANSI_WARNINGS ON

	CREATE TABLE dbo.Contact_ContactGroup(
		Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		ContactId INT,
		ContactGroupId INT);

	ALTER TABLE dbo.Contact_ContactGroup ADD CONSTRAINT [FK_ContactId] FOREIGN KEY(ContactId)
	REFERENCES Contact (Id)
	
	ALTER TABLE dbo.Contact_ContactGroup ADD CONSTRAINT [FK_ContactGroupId] FOREIGN KEY(ContactGroupId)
	REFERENCES ContactGroup (Id)

	COMMIT TRANSACTION [Contact_ContactGroupTable];
END TRY

BEGIN CATCH
	ROLLBACK TRANSACTION [Contact_ContactGroupTable]

	SELECT	ERROR_NUMBER() AS ErrorNumber,
			ERROR_SEVERITY() AS ErrorSeverity, 
			ERROR_STATE() AS ErrorState, 
			ERROR_PROCEDURE() AS ErrorProcedure, 
			ERROR_LINE() AS ErrorLine, 
			ERROR_MESSAGE() AS ErrorMessage;
END CATCH